export * from "./providers/token.ts";
export * from "./providers/wallet.ts";
export * from "./providers/trustScoreProvider.ts";
export * from "./evaluators/trust.ts";
import { Plugin } from "@ai16z/eliza";
import { TokenProvider } from "./providers/token.ts";
import { WalletProvider } from "./providers/wallet.ts";
export { TokenProvider, WalletProvider };
export declare const solanaPlugin: Plugin;
export default solanaPlugin;
