version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: AI
      POSTGRES_PASSWORD: AI
      POSTGRES_DB: eliza_test
    ports:
      - "5533:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_cache_size=768MB"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "checkpoint_timeout=1h"
      - "-c"
      - "max_wal_size=1GB"
      - "-c"
      - "min_wal_size=80MB"

volumes:
  postgres_data:
